dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://mysql:3306/shortlink?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ncu_inventory

rules:
  - !SHARDING
    tables:
      sl_link:
        actualDataNodes: ds_0.sl_link_${0..15}
        tableStrategy:
          standard:
            shardingColumn: gid
            shardingAlgorithmName: link_table_hash_mod
      sl_link_router:
        actualDataNodes: ds_0.sl_link_router_${0..15}
        tableStrategy:
          standard:
            shardingColumn: full_short_url
            shardingAlgorithmName: link_router_table_hash_mod
      sl_link_access_stats:
        actualDataNodes: ds_0.sl_link_access_stats_${0..15}
        tableStrategy:
          standard:
            shardingColumn: full_short_url
            shardingAlgorithmName: link_access_stats_table_hash_mod
    shardingAlgorithms:
      link_table_hash_mod:
        type: INLINE
        props:
          algorithm-expression: sl_link_${(gid.hashCode() & Integer.MAX_VALUE) % 16}
      link_router_table_hash_mod:
        type: INLINE
        props:
          algorithm-expression: sl_link_router_${(full_short_url.hashCode() & Integer.MAX_VALUE) % 16}
      link_access_stats_table_hash_mod:
        type: INLINE
        props:
          algorithm-expression: sl_link_access_stats_${(full_short_url.hashCode() & Integer.MAX_VALUE) % 16}
props:
  sql-show: true