dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://mysql:3306/shortlink?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ncu_inventory

rules:
  - !SHARDING
    tables:
      sl_user:
        actualDataNodes: ds_0.sl_user_${0..3}
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: user_table_hash_mod
      sl_group:
        actualDataNodes: ds_0.sl_group_${0..3}
        tableStrategy:
          standard:
            shardingColumn: username
            shardingAlgorithmName: group_table_hash_mod
    shardingAlgorithms:
      user_table_hash_mod:
        type: INLINE
        props:
          algorithm-expression: sl_user_${(username.hashCode() & Integer.MAX_VALUE) % 4}
      group_table_hash_mod:
        type: INLINE
        props:
          algorithm-expression: sl_group_${(username.hashCode() & Integer.MAX_VALUE) % 4}


  - !ENCRYPT
    tables:
      sl_user:
        columns:
          phone:
            cipher:
              name: phone
              encryptorName: phone_encryptor
          mail:
            cipher:
              name: mail
              encryptorName: mail_encryptor
    encryptors:
      phone_encryptor:
        type: AES
        props:
          aes-key-value: d6oadClrrb9A3GWo
          digest-algorithm-name: SHA-1
      mail_encryptor:
        type: AES
        props:
          aes-key-value: d6oadClrrb9A3GWo
          digest-algorithm-name: SHA-1
props:
  sql-show: true